# WARNING!! This is to build from source

# to use a version that is prebuilt copy one of the entries from the examples folder!


version: "3"
services:
  redis:
    image: redis
  ohmyform:
    build: .
    environment:
      CREATE_ADMIN: "TRUE"
      MAILER_URI: smtp://mail:1025
      DATABASE_DRIVER: postgres
      DATABASE_URL: postgresql://root:root@db:5432/ohmyform
      LOGIN_NOTE: "login with root:root!"
      SECRET_KEY: 12345
    links:
      - db
      - redis
      - mail
    ports:
      - "3000"
    depends_on:
      - db
      - redis
    labels:
          - "traefik.enable=true"
          - "traefik.http.routers.${JATAYUUUID}.rule=Host(`${JATAYUDOMAIN}`)"
          - "traefik.http.services.${JATAYUUUID}.loadbalancer.server.port=8536"
          - "traefik.http.routers.${JATAYUUUID}.tls.certResolver=myresolver"
          - "traefik.http.routers.${JATAYUUUID}.middlewares=Default-WAF@file"
  mail:
    image: mailhog/mailhog
    ports:
      - "8025"
  db:
    image: postgres:10-alpine
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ohmyform
